// adapters/vue/src/FlowEmbed.vue
<!--
  FlowEmbed.vue — @flow-designer/vue. The Vue slide face of the flow library.

  A thin <script setup> shell over @flow-designer/library/render's
  mountFlowAuto: mount on init, update() on flow-prop swap, destroy() on
  unmount. The kind-switch remount (single ↔ flow-set) and the visibility-gated
  rAF loop live in the library; this component only wires lifecycle. Public
  surface (flow, showMetrics) matches the Phase 2 embed so the deck/site
  wrappers barely change. Becomes @ribbonflow/vue at the repo split.
-->
<script setup>
import { onMounted, onBeforeUnmount, ref, watch } from 'vue'
import { mountFlowAuto } from '@flow-designer/library/render'

const props = defineProps({
  flow: { type: [Object, String], required: true },
  showMetrics: { type: Boolean, default: false },
})

const rootEl = ref(null)
let handle = null

onMounted(() => {
  handle = mountFlowAuto(rootEl.value, props.flow, { showMetrics: props.showMetrics })
})

// The deck's click idiom swaps the WHOLE `flow` prop (S4/S5/S11/S12). On that
// identity change, mountFlowAuto.update() rebuilds the scene (same kind) or
// remounts (kind switch) — the controller decides.
watch(
  () => props.flow,
  (next) => { if (handle) handle.update(next) },
)

onBeforeUnmount(() => {
  if (handle) handle.destroy()
  handle = null
})
</script>

<template>
  <div ref="rootEl" class="flow-embed"></div>
</template>

<style scoped>
.flow-embed { width: 100%; height: 100%; }
.flow-embed :deep(svg) { width: 100%; height: 100%; }
</style>

// adapters/react/src/FlowEmbed.jsx
// flow/adapters/react/src/FlowEmbed.jsx
import { useRef, useEffect } from 'react'
import { mountFlowAuto } from '@flow-designer/library/render'

/**
 * React <FlowEmbed> — renders a flow (or flow-set) through the imperative
 * renderer via @flow-designer/library's mountFlowAuto. The kind-switch remount
 * and the visibility-gated rAF loop live in the library; this is lifecycle
 * wiring only. Becomes @ribbonflow/react at the repo split.
 *
 * @param {{ flow: object|string, showMetrics?: boolean }} props
 */
export function FlowEmbed({ flow, showMetrics = false }) {
  const rootEl = useRef(null)
  const handle = useRef(null)
  const mounted = useRef(false)

  // Mount once; tear down on unmount. showMetrics is read at mount (matches the
  // Vue adapter, which watches only `flow`).
  useEffect(() => {
    handle.current = mountFlowAuto(rootEl.current, flow, { showMetrics })
    mounted.current = true
    return () => {
      if (handle.current) handle.current.destroy()
      handle.current = null
      mounted.current = false
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Swap on `flow` identity change — skip the initial run (mount already
  // rendered the first flow), so this fires only on a real prop swap.
  useEffect(() => {
    if (!mounted.current) return
    if (handle.current) handle.current.update(flow)
  }, [flow])

  return <div ref={rootEl} className="flow-embed" style={{ width: '100%', height: '100%' }} />
}
